version: '3'
services:
    php-apache-environment:
        container_name: main
        image: dexterquazi/capitalbeting.com
        depends_on:
            - db
        volumes:
            - ../:/var/www/html/
        ports:
            - 80:80
            - 443:443

    db:
      image: dexterquazi/redis
      ports:
        - '6379:6379'
      environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      volumes:
      - 'redis_data:/bitnami/redis/data'
volumes:
  redis_data:
    driver: local
    
